# Example config for training pipeline
# Save as configs/train.yaml

dataset:
  train_dir: data/train
  val_dir: data/val
  test_dir: data/test
  batch_size: 32
  image_size: [224, 224]
  augment: true

model:
  backbone: mobilenetv2
  weights: imagenet
  num_classes: 2

training:
  epochs_head: 5
  epochs_finetune: 10
  learning_rate_head: 0.001
  learning_rate_finetune: 0.0001
  early_stopping_patience: 3

checkpoint:
  dir: outputs/checkpoints
  best_model: mobilenetv2_best.h5
  log_csv: training_log.csv

logging:
  level: INFO

plots:
  dir: outputs/plots
